# Generated by Django 3.2.13 on 2022-05-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220516_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='code',
        ),
    ]
