# Generated by Django 3.2.13 on 2022-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='coupon',
            name='cart',
            field=models.ManyToManyField(to='inventory.Cart'),
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(to='inventory.Cart'),
        ),
    ]
