# Generated by Django 3.2.13 on 2022-05-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20220516_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(null=True, to='inventory.Product'),
        ),
    ]
