# Generated by Django 3.2.13 on 2022-05-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_cart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
